### ISSUE TITLE
Support for user-injected hyper client

### ISSUE THREAD

**Issue by rikonor** [instant-labs/instant-acme#23]
Hi!

What are your thoughts on supporting a user-injected hyper client? I'm referring to the client used [here](https://github.com/instant-labs/instant-acme/blob/main/src/lib.rs#L350).

**Comment by djc** [comment]
What's your use case? We can definitely consider it. I usually try to avoid making dependencies public since it means having to do semver-incompatible updates when the dependency does it, but in the case of hyper that's probably not a big deal.

**Comment by rikonor** [comment]
> What's your use case?

Thanks for the quick reply. In our case, we're hoping to use `instant-acme` as part of a much larger service, so it makes sense for us to be able to specify the transport it uses.

**Comment by djc** [comment]
Will you still use the same `C` for `hyper::client::Client<C>` or will the `Account` need to be parametrized with the `Connect` type? That would get a little ugly (I can't quickly figure out if `Connect` is object-safe).

**Comment by Daniel-Bloom-dfinity** [comment]
It would be nice to be able to use any `C`. If I were implementing this, I'd probably add something like:

```rust
trait HyperClient: std::fmt::Debug {
    fn get(&self, uri: hyper::Uri) -> ResponseFuture;
    fn request(&self, req: Request<Body>) -> ResponseFuture;
}

impl<C> HyperClient for hyper::Client<C, Body> where
    C: hyper::client::connect::Connect + Clone + Send + Sync + 'static {
    fn get(&self, uri: hyper::Uri) -> ResponseFuture {
        <hyper::Client<_>>::get(&self, uri)
    }
    fn request(&self, req: Request<Body>) -> ResponseFuture {
        <hyper::Client<_>>::request(&self, req)
    }
}
```

You can even keep the trait private and make the constructor functions generic over `C`, but then `Box<dyn>`it.

**Comment by djc** [comment]
I'd still like to better understand what C you're looking to use here.

**Comment by Daniel-Bloom-dfinity** [comment]
Oh,  strictly speaking I think we are using `hyper_rustls::HttpsConnector<HttpConnector>` at the moment, but there have been occasions where we've needed to use a custom resolver, which in our case makes the type `hyper_rustls::HttpsConnector<HttpConnector<ServiceFn<impl Fn(Name) -> impl Future<Output = Result<Either<Once<SocketAddr>, GaiAddrs>, Error>>>>`

**Comment by djc** [comment]
@Daniel-Bloom-dfinity @rikonor please have a look at #24.

**Comment by rikonor** [comment]
Hi @djc, thanks so much again for doing this work - and for the recent fix (0.3.2).

In some of our tests, I am attempting to mock the http client (this is a specific testing environment that is not able to connect to Let's Encrypt) such that it will return a set of pre-defined responses for `/directory`, `/new-nonce`, `/new-acct`, etc.

That said, I now realize that it's not possible afaict to create a `ResponseFuture` due to `ResponseFuture::new` being a private function, so e.g in the following example:

```rs
struct AcmeClient(Client<HttpsConnector<HttpConnector>>);

impl HttpClient for AcmeClient {
    fn request(&self, req: Request<Body>) -> ResponseFuture {
        self.0.request(req)
    }
}
```

It's not actually possible to return a custom response. Was just wondering if I'm completely mistaken or if I'm not, if you had any thoughts. Thanks again!

**Comment by djc** [comment]
@rikonor makes sense. Want to add an associated type for this to `HttpClient`?

**Comment by Daniel-Bloom-dfinity** [comment]
> @rikonor makes sense. Want to add an associated type for this to `HttpClient`?

Sounds like a plan to me. I'll draft up an MR.
