### ISSUE TITLE
missing nonce when running against pebble

### ISSUE THREAD

**Issue by rikonor** [instant-labs/instant-acme#30]
Hi!

I have the following local test setup.

1. Create a key-pair for `pebble` via:
```sh
mkcert localhost
```

2. Run `pebble` via:
```sh
docker run \
		--rm -it \
		--name pebble \
		-p 14000:14000 \
		-e PEBBLE_VA_NOSLEEP=1 \
		-v ${PWD}/acme/pebble-config.json:/pebble-config.json:ro \
		-v ${PWD}/acme/localhost-key.pem:/localhost-key.pem:ro \
		-v ${PWD}/acme/localhost.pem:/localhost.pem:ro \
		letsencrypt/pebble pebble \
			-config /pebble-config.json \
			-dnsserver coredns:53 \
			-strict  
```
with the following `pebble-config.json`:
```json
{
    "pebble": {
        "listenAddress": "0.0.0.0:14000",
        "managementListenAddress": "0.0.0.0:15000",
        "certificate": "/localhost.pem",
        "privateKey": "/localhost-key.pem",
        "httpPort": 5002,
        "tlsPort": 5001,
        "ocspResponderURL": "",
        "externalAccountBindingRequired": false,
        "domainBlocklist": [],
        "retryAfter": {
            "authz": 3,
            "order": 5
        }
    }
}
```

Then when running the following Rust code:
```rs
use anyhow::{anyhow, Context, Error};
use instant_acme::{
    Account, AccountCredentials, Authorization, Challenge, ChallengeType, Identifier, NewOrder,
};

#[tokio::main]
async fn main() -> Result<(), Error> {
    let acme_provider_url = "https://localhost:14000";
    let acme_account_id = "blah blah";
    let acme_account_key = "blah blah";

    let acme_credentials: AccountCredentials = serde_json::from_str(&format!(
        r#"{{
            "id": "{acme_provider_url}/acme/acct/{acme_account_id}",
            "key_pkcs8": "{acme_account_key}",
            "urls": {{
                "newNonce": "{acme_provider_url}/acme/new-nonce",
                "newAccount": "{acme_provider_url}/acme/new-acct",
                "newOrder": "{acme_provider_url}/acme/new-order"
            }}
        }}"#,
    ))?;

    let acme_account = Account::from_credentials(acme_credentials)
        .context("failed to create acme account from credentials")?;

    // Get Order
    let mut order = acme_account
        .new_order(&NewOrder {
            identifiers: &[Identifier::Dns("example.com".to_string())],
        })
        .await
        .context("failed to create new order")?;

    Ok(())
}
```
I get the following error:
```sh
Error: failed to create new order

Caused by:
    missing data: no nonce found
```

I tracked it down to the fact that the initial `new_order` call [doesn't send a nonce](https://github.com/instant-labs/instant-acme/blob/main/src/lib.rs#L303). Any idea if this is the expected behavior or whether the library should first retrieve a nonce via `/newNonce`?

Wondering if I'm just doing something wrong here when running against pebble?

**Comment by rikonor** [comment]
Ok, I think I'm narrowing down on the problem - I am using the following to create the `AccountCredentials`:
```rs
let acme_credentials: AccountCredentials = serde_json::from_str(&format!(
    r#"{{
        "id": "{acme_provider_url}/acme/acct/{acme_account_id}",
        "key_pkcs8": "{acme_account_key}",
        "urls": {{
            "newNonce": "{acme_provider_url}/acme/new-nonce",
            "newAccount": "{acme_provider_url}/acme/new-acct",
            "newOrder": "{acme_provider_url}/acme/new-order"
        }}
    }}"#,
))?;
```
which hardcodes the endpoint paths... Pebble uses different paths on purpose... e.g. `/nonce-plz`.

**Comment by djc** [comment]
Right, so you provided an incorrect `newNonce` path and the error about that is kind of opaque. See #31 for an attempt to somewhat improve the error handling here.

**Comment by rikonor** [comment]
@djc So one thing I've noticed - when creating a new account, instant-acme will retrieve the correct URLs from the ACME server... That said, there seems to be no way at the moment to _import_ an account without also specifying the URLs (this is because importing/exporting is just done via serializing/deserializing the AccountCredentials struct. It would be nice if there was a way to import an account just via a subset of fields, e.g the provider URL and/or the account key, and still have the crate retrieve the correct URLs from the directory.

**Comment by djc** [comment]
Why do you want that? The library considers the serialized data mostly as an opaque blob, and doesn't currently keep the the provider URL around at all in the `Client`/`Account` context (because it isn't needed).

**Comment by djc** [comment]
How are you storing/passing in the key? I'm open to providing API for constructing an `Account` with a provider URL, ID and existing key, but the main issue I saw there is that it wasn't obvious to me how people are storing their keys.

**Comment by rikonor** [comment]
Hi @djc, we have a utility for generating credentials, `create-acme-credentials` that uses `instant-acme` just to create and output credentials to stdout. We only grab the account ID and key from this output.

We then use those for running multiple instances of a service, so that they all use the same ACME credentials, i.e:
```sh
my-service \
    --acme-provider-url "${ACME_URL}" 
    --acme-account-id "${ACME_ID}" 
    --acme-account-key "${ACME_KEY}"
```

That said, that's not enough information, we would need to provide the paths for `new-nonce`, `new-order`, etc. We could do this, although I argue that it'd be better if the library just retrieved the paths itself.

**Comment by djc** [comment]
What I guess I'm confused about is why your utility only captures part of the serialized `AccountCredentials` instead of the whole thing? That is the way it was intended, as the documentation explains:

> This opaque type contains the account ID, the private key data and the server URLs from the relevant ACME server. This can be used to serialize the account credentials to a file or secret manager and restore the account from persistent storage.

**Comment by rikonor** [comment]
> What I guess I'm confused about is why your utility only captures part of the serialized AccountCredentials instead of the whole thing?

You're correct that if we just use the opaque credentials blob, this is resolved. And I suppose we could do that. Although to be fair, it also seems reasonable to have the crate fetch the actual directory when creating an account.

I think the ideal scenario would be that the crate exposes a builder that lets you specify whatever you want. A `ClientBuilder` or `AccountBuilder` with a bunch of `.with_directory_url(dir_url: &str)`, `.with_credentials(id: &str, key: &str)`, `.with_credentials(creds: AccountCredentials)`, `.with_http_client(client: &HttpClient)`, etc.

**Comment by djc** [comment]
That doesn't solve the problem of how the key should be serialized. You also didn't really answer the question of why your code doesn't store the all of the `AccountCredentials` today.

**Comment by rikonor** [comment]
> You also didn't really answer the question of why your code doesn't store the all of the AccountCredentials today.

For various reasons, our service can't accept a file as a cli argument, therefore we give it the account ID and key instead, which seems like a pretty common thing, just as common as providing credentials via a file.

I'm sure we could work around this limitation, e.g. provide the file contents directly, etc, we just can't have the service read the file, unfortunately, which is why I brought this up.

**Comment by djc** [comment]
See if #34 makes things easier for you?
