### ISSUE TITLE
Unable to create Acme / LetsEncrypt account

### ISSUE THREAD

**Issue by joepio** [instant-labs/instant-acme#49]
```rust
    let (account, _creds) = instant_acme::Account::create(
        &instant_acme::NewAccount {
            contact: &[&format!("mailto:{}", email)],
            terms_of_service_agreed: true,
            only_return_existing: false,
        },
        instant_acme::LetsEncrypt::Production.url()
        None,
    )
    .await
    .map_err(|e| format!("Failed to create LetsEncrypt account: {}", e))?;
```

`Error: Failed to create account: HTTP request failure: error trying to connect: dns error: failed to lookup address information: Try again`

I think this means that for some reason the DNS of either LetsEncrypt or my own server is failing.

**Comment by djc** [comment]
It sounds like the environment this code runs in is failing to lookup the Let's Encrypt IP. Not much this library can do about that.

**Comment by joepio** [comment]
Thanks for the quick reply. Closing!
